# This file was generated by GoReleaser. DO NOT EDIT.
cask "andamio-cli" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "50aba30c33737ebde7eaf562627fd024420ae7c3595f672c87bd1e6e6993583a"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80e103fecf6ae9e35c4bf60b42924b764773dceca023c0ca7b050f8f000b9378"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76e54f67917dcdfd221b3c48b993f067d7e2b4212d9220db5a1a36c37cca5d7d"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3e2bdc320277fa939352e24dbb1c7e33d81e40d823db5f2cbbcf67414c88ddf"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "andamio-cli"
  desc "CLI for the Andamio Protocol"
  homepage "https://github.com/Andamio-Platform/andamio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andamio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andamio"]
    end
  end

  # No zap stanza required

end
