# This file was generated by GoReleaser. DO NOT EDIT.
cask "andamio-cli" do
  name "andamio-cli"
  desc "CLI for the Andamio Protocol"
  homepage "https://github.com/Andamio-Platform/andamio-cli"
  version "0.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andamio"

  on_macos do
    on_intel do
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_amd64.tar.gz"
      sha256 "77fa8057281d907bdd0cdb001b25795516119c8fa109d89e7fc5eb59e470478b"
    end
    on_arm do
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_arm64.tar.gz"
      sha256 "634fb8b8109b43d14f483dc938b5534cb730fcedafcf2a27bab755f61ed5dc7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_amd64.tar.gz"
      sha256 "fe4329e7e1f8d196561d572434676f15ace765faa2a4f33e7611edeee70fee93"
    end
    on_arm do
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_arm64.tar.gz"
      sha256 "db70da235a854002caf059f42cad6d0e70542b19770ac9a613ed177b960edd2a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andamio"]
    end
  end

  # No zap stanza required
end
