# This file was generated by GoReleaser. DO NOT EDIT.
cask "andamio-cli" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "d7f344d9996d316c8ef1288eb1924a90e0901e48f61989c58d0726b83fa0085e"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb232b558cc34251fd98555fb4fa5662377c1dd5de452a7a3fd944447d4b67a6"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ecd575598b1aa08427ba06b7d9b860402cae2322c104c59ce4d8fe8ae2aaa10"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c73bbf654fdd7a51366fb751b66f65f87f3fc9dbc2503e1039d60a8469d8ba0"
      url "https://github.com/Andamio-Platform/andamio-cli/releases/download/v#{version}/andamio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "andamio-cli"
  desc "CLI for the Andamio Protocol"
  homepage "https://github.com/Andamio-Platform/andamio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andamio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andamio"]
    end
  end

  # No zap stanza required
end
